// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryWebAPI.Data;

#nullable disable

namespace MusicLibraryWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryWebAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Beck",
                            Title = "The Golden Age"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Beck",
                            Title = "Paper Tiger"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Beck",
                            Title = "Guess I'm Doing Fine"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Beck",
                            Title = "Lonesome Tears"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Beck",
                            Title = "Lost Cause"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Beck",
                            Title = "End of the Day"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Beck",
                            Title = "It's All in Your Mind"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Beck",
                            Title = "Round the Bend"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Beck",
                            Title = "Already Dead"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Beck",
                            Title = "Sunday Sun"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Beck",
                            Title = "Little One"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "Beck",
                            Title = "Side of the Road"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
